// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Layout(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/templates/layout.templ`, Line: 9, Col: 16}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " — kvik-tasks</title><link rel=\"stylesheet\" href=\"/static/css/kviky.css\"><link rel=\"stylesheet\" href=\"/static/css/lucide.css\"><link rel=\"stylesheet\" href=\"/static/css/style.css\"><script src=\"/static/js/htmx.min.js\"></script><script src=\"/static/js/json-enc.js\"></script></head><body><div class=\"kvt-app\"><aside class=\"kvt-sidebar\"><a href=\"/\" class=\"kvt-sidebar-logo\">kvt</a><nav class=\"kvt-sidebar-nav\"><a href=\"/\" class=\"kvt-sidebar-link\" title=\"Dashboard\"><i class=\"icon icon-layout-dashboard\"></i></a> <a href=\"/\" class=\"kvt-sidebar-link\" title=\"Settings\"><i class=\"icon icon-settings\"></i></a></nav></aside><div class=\"kvt-main\"><header class=\"kvt-topbar\"><div class=\"kvt-topbar-actions\"><a href=\"/\">Dashboard</a></div><div class=\"kvt-topbar-title\">kvik-tasks</div></header><main class=\"kvt-content\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</main></div></div><script>\n\tdocument.body.addEventListener('htmx:afterRequest', function(e) {\n\t\tvar el = document.getElementById('save-indicator');\n\t\tif (el && e.detail.elt.closest && e.detail.elt.closest('.kvt-task-layout, .kvt-toolbar')) {\n\t\t\tel.textContent = 'Saved';\n\t\t\tel.classList.add('kvt-save-indicator--visible');\n\t\t\tclearTimeout(el._t);\n\t\t\tel._t = setTimeout(function() {\n\t\t\t\tel.classList.remove('kvt-save-indicator--visible');\n\t\t\t}, 2000);\n\t\t}\n\t});\n\t</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
